# Replication Controller for springapp
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: sureshaho/spring-boot-mongo-docker
        name: springboot
        ports:
        - containerPort: 8080  
---
# Node Port Service For SpringApp
apiVersion: apps/v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
# Mongo RC with host path Volume
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: mongo-controller
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
---
# Mongo Node Port RC
apiVersion: apps/v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
